# => Build container
FROM registry.cn-beijing.aliyuncs.com/comall/backend:build as builder

# => Runtime container
FROM harbor.product.co-mall/cae/nginx-front:1.16.1
RUN rm -rf /etc/nginx/nginx.conf
COPY --from=builder /app/node_modules/@comall-backend-builder/scaffold/nginx/nginx.conf /etc/nginx/
RUN rm -rf /etc/nginx/conf.d
COPY --from=builder /app/node_modules/@comall-backend-builder/scaffold/nginx/conf.d /etc/nginx/conf.d
COPY --from=builder /app/build /usr/share/nginx/html/
RUN mkdir -p /tmp/log
RUN touch /tmp/log/access_log.json
EXPOSE 8080
WORKDIR /usr/share/nginx/html
RUN chmod +x env.sh
CMD ["/bin/bash", "-c", "/usr/share/nginx/html/env.sh && nginx -g \"daemon off;\""]
